<%@ Page Title="" Language="C#" MasterPageFile="~/CMS.Master" AutoEventWireup="true" CodeBehind="EventMaintenance.aspx.cs" Inherits="SEM.CMS.Web.EventMaintenance" %>

<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="asp" %>

<%@ MasterType VirtualPath="~/CMS.Master" %>

<asp:Content ID="Content1" ContentPlaceHolderID="CPH_CMS" runat="server">
    <fieldset id="fieldSetSearch" runat="server" visible="false">
        <legend>Search</legend>
        <table>
            <tr>
                <td>Event&nbsp;&nbsp;
                </td>
                <td>
                    <asp:TextBox runat="server" ID="txtEvent" />
                </td>
            </tr>
        </table>
    </fieldset>
    <div class="form-actions">
    <asp:Button runat="server" ID="btnSearch" Text="Search" OnClick="btnSearch_Click" Visible="false" />
    <asp:Button ID="btnNew" Text="New" runat="server" OnClick="btnNew_Click" Visible="false"/></div>
    <div class="widget-body"><div class="form"><div class="form-horizontal">
    <asp:GridView ID="dgEventDetail"  runat="server" EnableViewState="true"
        AutoGenerateColumns="false"
        AutoGenerateDeleteButton="true" 
        AllowPaging="true"
        OnRowDeleting="DGEventDetail_RowDeleting"
        OnPageIndexChanging="DGEventDetail_PageIndexChanging" 
        DataKeyNames="SportID,EventID,GenderID,PlayFormatID,EventTypeID"
        CssClass="table table-striped table-bordered"
        >
        <Columns>
                <asp:TemplateField HeaderText="No." ItemStyle-Width="20px">
                    <ItemTemplate>
                        <%# Container.DataItemIndex + 1 %>
                    </ItemTemplate>
                </asp:TemplateField>
            </Columns>
    </asp:GridView></div>
    <div id="divfileUpload" runat="server" class="form-actions">
    Bulk Upload Schedule for Sport <br />
    <asp:FileUpload ID="btnFileUpload" runat="server" />
    <asp:Button ID="btnLoadFromCsv" runat="server" OnClick="btnLoadFromCsv_Click" Text="Load From CSV" />
        </div>
</asp:Content>
