<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="StartList.aspx.cs" Inherits="SEM.CMS.Web.Competition.StartList" MasterPageFile="../CMS.Master" %>

<%@ Register Assembly="CKEditor.NET" Namespace="CKEditor.NET" TagPrefix="CKEditor" %>
<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="asp" %>

<%@ MasterType VirtualPath="~/CMS.Master" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="CPH_CMS" runat="server">  
    <asp:Image ID="imgSportImage" runat="server" Height="60px" Width="60px" />
    <asp:Label ID="lblEventDetails" runat="server"></asp:Label><br />
    <asp:Label runat="server" ID="lblScheduleDetails"></asp:Label><br />
    <asp:Label runat="server" ID="lblScheduleVenueTime"></asp:Label><br />
    <br />
    <br />
    <div id="page" class="dashboard">
        <div class="row-fluid">
            <!-- BEGIN Choose Participant List Source-->
						<div class="span12">
							<div class="widget">
								<div class="widget-title">
									<h4><i class="icon-reorder"></i>Add Participant</h4>
									<span class="tools">
									<a href="javascript:;" class="icon-chevron-down"></a>
									</span>							
								</div>
								<div class="widget-body">
									<div class="form form-horizontal">
                                        <div class="control-group">
                                <label class="control-label">Select Source</label>
                                            <div class="controls">
                                                <asp:DropDownList class="span6" ID="ddlSourceName" OnSelectedIndexChanged="ddlSourceName_OnSelectedIndexChanged" AutoPostBack="true" runat="server">
                                                    <asp:ListItem Text="" Value=""></asp:ListItem>
                                                    <asp:ListItem Text="Participant In Event" Value="dgStartListAddParticipant"></asp:ListItem>
                                                </asp:DropDownList>
                                            </div>
                                        </div>

                                        <asp:Button ID="btnAddMultipleParticipant" class="btn" runat="server" Text="Add Start List" Visible="false" OnClick="btnAddMultipleParticipant_Click" />
                      
									</div>
                                    <br />
                        <asp:GridView ID="dgStartListAddParticipant" runat="server" EnableViewState="true"
                                        AutoGenerateColumns="false"
                                        AutoGenerateDeleteButton="false" 
                                        AutoGenerateEditButton="false" 
                                        DataKeyNames="ParticipantID"
                            class="table table-striped table-bordered">
                                        <Columns>
                                                <asp:TemplateField HeaderText="Add" ItemStyle-Width="5px">
                                                    <ItemTemplate>
                                                        <asp:CheckBox ID="chkAdd" runat="server" />
                                                    </ItemTemplate>
                                                </asp:TemplateField>
                                            </Columns>
                                    </asp:GridView>
								</div>
							</div>
						</div>
            <!-- END Choose Participant List Source-->
        </div>
        <div class="row-fluid">
            <!-- BEGIN GridView-->
						<div class="span12">
							<div class="widget">
								<div class="widget-title">
									<h4><i class="icon-reorder"></i>Details</h4>
									<span class="tools">
									<a href="javascript:;" class="icon-chevron-down"></a>
									</span>							
								</div>
								<div class="widget-body">
                    <div style="overflow-x: scroll; margin-right: 3px;">
                        <asp:GridView ID="dgStartListMaintenance" runat="server" EnableViewState="true"
                                        AutoGenerateColumns="false"
                                        AutoGenerateEditButton="false"
                                        OnRowDeleting="DGStartListMaintenance_RowDeleting"
                                        OnRowDataBound="dgStartListMaintenance_RowDataBound"
                                        DataKeyNames="ParticipantInScheduleID"
                            class="table table-striped table-bordered">
                                        <Columns>
                                                <%--<asp:TemplateField HeaderText="Assign Team" ItemStyle-Width="5px">
                                                    <ItemTemplate>
                                                        <asp:CheckBox ID="chkAssignTeam" runat="server" />
                                                    </ItemTemplate>
                                                </asp:TemplateField>--%>
                                                <asp:CommandField ShowDeleteButton="True" 
                                    ItemStyle-Width="20px" />
                                        </Columns>
                                    </asp:GridView>
                    </div>
                                        <asp:HiddenField ID="hidStartListNameID" runat="server" />
                        <asp:TextBox ID="HiddenTxtTeamID" Style="display: none" runat="server" ClientIDMode="Static"></asp:TextBox>
                        <asp:TextBox ID="HiddenTxtParticipantID" Style="display: none" runat="server" ClientIDMode="Static"></asp:TextBox>
                        <asp:TextBox ID="HiddenTxtScheduleID" Style="display: none" runat="server" ClientIDMode="Static"></asp:TextBox>
                        <asp:TextBox ID="HiddenTxtSortID" Style="display: none" runat="server" ClientIDMode="Static"></asp:TextBox>
                        <asp:Button ID="HiddenBtnUp" runat="server" Text="Button" Style="display: none" OnClick="HiddenBtnUp_Click" ClientIDMode="Static" />
                        <asp:Button ID="HiddenBtnDown" runat="server" Text="Button" Style="display: none" OnClick="HiddenBtnDown_Click" ClientIDMode="Static" />

								</div>
							</div>
                        </div>
            <!-- END Gridview-->
        </div>
        <div class="row-fluid">
            <asp:Label ID="Label1" runat="server" Text="Start List Footer Note :"></asp:Label>
            <CKEditor:CKEditorControl ID="ckeStarlistFooter" BasePath="/ckeditor/" runat="server"></CKEditor:CKEditorControl>
        </div>
    </div>
    <div class="form-actions">
        <asp:Button ID="btnBack" Text="Back" class="btn btn-success" runat="server" OnClick="btnBack_Click" />
        <asp:Button ID="btnUpdate" Text="Update Startlist" class="btn btn-primary" runat="server" OnClick="btnUpdate_Click" />
        <asp:Button ID="btnResult" Text="Edit Result" class="btn btn-primary" runat="server" OnClick="btnResult_Click" />
    </div>

    <script type="text/javascript">  
    // for calling code behind method  
        function Up(teamID, participantID, scheduleID, sortID) {
            document.getElementById('<%= HiddenTxtTeamID.ClientID %>').value = teamID;
            document.getElementById('<%= HiddenTxtParticipantID.ClientID %>').value = participantID;
            document.getElementById('<%= HiddenTxtScheduleID.ClientID %>').value = scheduleID;
            document.getElementById('<%= HiddenTxtSortID.ClientID %>').value = sortID;

            var hdnbtn = document.getElementById("HiddenBtnUp");
            hdnbtn.click();
        }
        function Down(teamID, participantID, scheduleID, sortID) {
            document.getElementById('<%= HiddenTxtTeamID.ClientID %>').value = teamID;
            document.getElementById('<%= HiddenTxtParticipantID.ClientID %>').value = participantID;
            document.getElementById('<%= HiddenTxtScheduleID.ClientID %>').value = scheduleID;
            document.getElementById('<%= HiddenTxtSortID.ClientID %>').value = sortID;

            var hdnbtn = document.getElementById("HiddenBtnDown");
            hdnbtn.click();
        }
    </script>   

</asp:Content>
