<%@ Page Title="" Language="C#" MasterPageFile="~/CMS.Master" AutoEventWireup="true" CodeBehind="AdminUserMaintenance.aspx.cs" Inherits="SEM.CMS.Web.AdminUserMaintenance" %>

<asp:Content ID="Content1" ContentPlaceHolderID="CPH_CMS" runat="server">
    <asp:Button ID="btnNew" Text="New" runat="server" OnClick="btnNew_Click" />
    <asp:GridView ID="dgAdminUserDetail"  runat="server" EnableViewState="true"
        AutoGenerateColumns="false"
        AutoGenerateDeleteButton="true" 
        AllowPaging="true"
        OnRowDeleting="DGAdminUserDetail_RowDeleting"
        OnPageIndexChanging="DGAdminUserDetail_PageIndexChanging" 
        class="table table-striped table-bordered"
        DataKeyNames="AdminUserID,LoginID">
        <Columns>
                <asp:TemplateField HeaderText="No." ItemStyle-Width="20px">
                    <ItemTemplate>
                        <%# Container.DataItemIndex + 1 %>
                    </ItemTemplate>
                </asp:TemplateField>
            </Columns>
    </asp:GridView>
</asp:Content>
