<%@ Page Title="" Language="C#" MasterPageFile="~/CMS.Master" AutoEventWireup="true" CodeBehind="FunctionalModuleMaintenance.aspx.cs" Inherits="SEM.CMS.Web.Admin.FunctionalModuleMaintenance" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="CPH_CMS" runat="server">
    <table style="width: 500px">
        <colgroup>
            <col style="width: 30px" />
            <col style="width: 250px" />
            <col style="width: 10px" />
            <col style="width: 200px" />
        </colgroup>
        <tr>
            <td></td>
            <td colspan="3">
                <asp:Button ID="btnBack" Text="Back" runat="server" OnClick="btnBack_Click" />
                &nbsp;
                <asp:Button ID="btnClear" Text="Clear" runat="server" OnClick="btnClear_Click" /></td>
        </tr>
        <tr>
            <td></td>
            <td colspan="3" style="font-weight: bold">Functional Module</td>
        </tr>
        <tr>
            <td></td>
            <td>Module Name</td>
            <td>:</td>
            <td>
                <asp:TextBox ID="txtModuleName" runat="server" Width="200px" CssClass="span12"></asp:TextBox></td>
        </tr>
        <tr>
            <td></td>
            <td>Functional Name</td>
            <td>:</td>
            <td>
                <asp:TextBox ID="txtFunctionalName" runat="server" Width="200px"></asp:TextBox></td>
        </tr>
        <tr>
            <td></td>
            <td>Page Name</td>
            <td>:</td>
            <td>
                <asp:TextBox ID="txtPageName" runat="server" Width="200px"></asp:TextBox></td>
        </tr>
        <tr>
            <td>&nbsp;</td>
        </tr>
    </table>
    <div class="form-actions">
        <asp:Button ID="btnInsert" Text="Insert Module" CssClass="btn btn-primary" runat="server" OnClick="btnInsert_Click" /></div>
    <br />
    <table>
        <colgroup>
            <col style="width: 30px" />
            <col style="width: 150px" />
            <col style="width: 10px" />
            <col style="width: 200px" />
        </colgroup>
        <tr>
            <td></td>
            <td>Page</td>
            <td>:</td>
            <td>
                <asp:DropDownList ID="ddlPageName" OnSelectedIndexChanged="ddlPageName_OnSelectedIndexChanged" AutoPostBack="true" Width="200px" runat="server">
                    <asp:ListItem Text="All" Value=""></asp:ListItem>
                </asp:DropDownList></td>
        </tr>
    </table>
    <br />
    <br />
    <asp:GridView ID="dgModuleFunction" runat="server" EnableViewState="true"
        class="table table-striped table-bordered"
        AutoGenerateColumns="false"
        AutoGenerateDeleteButton="true"
        AutoGenerateEditButton="true"
        AllowPaging="true"
        OnRowCancelingEdit="DGModuleFunction_RowCancelingEdit"
        OnRowDeleting="DGModuleFunction_RowDeleting"
        OnRowEditing="DGModuleFunction_RowEditing"
        OnRowUpdating="DGModuleFunction_RowUpdating"
        OnPageIndexChanging="DGModuleFunction_PageIndexChanging"
        DataKeyNames="ModuleID">
        <Columns>
            <asp:TemplateField HeaderText="No." ItemStyle-Width="20px">
                <ItemTemplate>
                    <%# Container.DataItemIndex + 1 %>
                </ItemTemplate>
            </asp:TemplateField>
        </Columns>
    </asp:GridView>
</asp:Content>
