<%@ Page Title="" Language="C#" MasterPageFile="~/CMS.Master" AutoEventWireup="true" CodeBehind="RoleMaintenance.aspx.cs" Inherits="SEM.CMS.Web.Admin.RoleMaintenance" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="CPH_CMS" runat="server">
    <asp:Button ID="btnNew" Text="New" runat="server" OnClick="btnNew_Click" />
    <asp:GridView ID="dgRoleDetail"  runat="server" EnableViewState="true"
        class="table table-striped table-bordered"
        AutoGenerateColumns="false"
        AutoGenerateDeleteButton="true" 
        AllowPaging="true"
        OnRowDeleting="DGRoleDetail_RowDeleting"
        OnPageIndexChanging="DGRoleDetail_PageIndexChanging" 
        DataKeyNames="RoleID">
        <Columns>
                <asp:TemplateField HeaderText="No." ItemStyle-Width="20px">
                    <ItemTemplate>
                        <%# Container.DataItemIndex + 1 %>
                    </ItemTemplate>
                </asp:TemplateField>
            </Columns>
    </asp:GridView>
</asp:Content>
